[toolchain]
anchor_version = "0.32.0"
solana_version = "2.2.11"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lode_token = "ANxSnSKr6VBXw7dEaW9P3utWbXxoH2jxctgA1sXtPyL8"
lode_treasury = "HjRCbiKYNa61Mee6Hbxy5tGCPzDBrzNcaZjVRGcPcSFC"
lode_mining = "CSrYQ2uEURizXFDruLVyHUXcNN1Dv3XKFdbPnddMF2pB"

[programs.devnet]
lode_token = "ANxSnSKr6VBXw7dEaW9P3utWbXxoH2jxctgA1sXtPyL8"
lode_treasury = "HjRCbiKYNa61Mee6Hbxy5tGCPzDBrzNcaZjVRGcPcSFC"
lode_mining = "CSrYQ2uEURizXFDruLVyHUXcNN1Dv3XKFdbPnddMF2pB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
